swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Get User Accounts
      description: API for retrieving the list of bank accounts associated with the authenticated user.
      produces:
        - application/json
      responses:
        '200':
          description: Accounts retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        '400':
          description: Invalid fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transactions for a specific account
      description: API for fetching transactions for a specific account
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: The ID of the account to fetch transactions for.
      responses:
        '200':
          description: Successfully retrieved account transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get detailed information of a specific transaction
      description: API to fetch details of a specific transaction
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: The ID of the account associated with the transaction.
        - name: transactionId
          in: path
          required: true
          type: string
          description: The ID of the transaction to fetch details for.
      responses:
        '200':
          description: Successfully retrieved transaction details
          schema:
            $ref: '#/definitions/TransactionDetails'
        '400':
          description: Invalid account or transaction ID
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionId}/category:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction category
      description: Assign a new category to a specific transaction
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: The ID of the account
        - name: transactionId
          in: path
          required: true
          type: string
          description: The ID of the transaction
        - in: body
          name: category
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
                description: Category to assign to the transaction
      responses:
        '200':
          description: Category updated successfully
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionId}/note:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Add or update a note for a specific transaction
      description: API to add or update the note for a particular transaction
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: The ID of the account
        - name: transactionId
          in: path
          required: true
          type: string
          description: The ID of the transaction
        - in: body
          name: body
          description: Note details
          required: true
          schema:
            type: object
            properties:
              note:
                type: string
                description: The note to be added or updated
      responses:
        '200':
          description: Successfully updated note
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete the note for a specific transaction
      description: API to delete the note for a specific transaction
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: The ID of the account 
        - name: transactionId
          in: path
          required: true
          type: string
          description: The ID of the transaction 
    responses:
      '200':
        description: Successfully deleted note
      '400':
        description: Invalid fields
      '500':
        description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Account:
    type: object
    properties:
      id:
        type: string
        description: Unique account identifier
      accountType:
        type: string
        description: Type of the account (checking, savings)
      accountNumber:
        type: string
        description: Bank account number
      balance:
        type: number
        description: Current account balance
  Transaction:
    type: object
    properties:
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description for the transaction
      amount:
        type: number
        format: float
        description: Amount of the transaction
      balance:
        type: number
        format: float
        description: Balance after the transaction
  TransactionDetails:
    type: object
    properties:
      transactionId:
        type: string
      transactionType:
        type: string
        description: Type of the transaction
      category:
        type: string
        description: Category of the transaction
      availableCategories:
        type: array
        items:
          type: string
      note:
        type: string
        description: Optional note for the transaction
    
